# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Nerd

general {
    hide_cursor = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Downloads/Wallpaper3.png
    blur_passes = 1
    blur_size = 1
}

input-field {
    size = 20%, 5%

    outline_thickness = 2

    inner_color = rgba(2E3137aa)

    outer_color = rgba(2EBBFFff)

    font_color = rgb(143, 143, 143)

    rounding = 0

    font_family = Comic

    placeholder_text = PASSWORD

    fail_text = $PAMFAIL$FPRINTFAIL

    fade_on_empty = false

    check_text = CHECKING ...

    dots_text_format = ~

    dots_size = 0.4
    dots_spacing = 0

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    text = $TIME
    font_size = 40
    color = rgba(2EBBFFff)
    font_family = Mono

    position = 0, -10
    halign = center
    valign = top
}

# # DATE
# label {
#     monitor =
#     text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
#     font_size = 25
#     font_family = $font
# 
#     position = -30, -150
#     halign = right
#     valign = top
# }

label {
    text = $LAYOUT[en,ru]
    font_size = 20
    onclick = hyprctl switchxkblayout all next

    position = 170, -20
    halign = center
    valign = center
    color = rgba(2EBBFFff)
    zindex = 1
}

shape {
    monitor = 
    size = 50, 38
    color = rgba(2E3137ff)
    rounding = 0
    border_size = 2
    border_color = rgba(2EBBFFff)
    position = 170, -20
    halign = center
    valign = center
    zindex = 0

}
